language: ruby

matrix:
  allow_failures:
    - rvm: rbx
    - rvm: truffleruby-head

rvm:
  - 2.0.0
  - 2.3.1
  - ruby-head
  - jruby
  - rbx
  - ree
  - truffleruby-head

script: "bundle exec shindont"
